"""Kurulum sihirbazı — donmuş ikilinin **içinden**, kabuksuz.

`setup.sh` Linux'ta bash'tir ve orada doğru şeydir: waybar config'ini cerrahi düzenler,
Hyprland autostart'ı yazar, tepsiyi kurar. Windows'ta kullanıcının elinde **tek bir dosya**
vardır — `usage-tracker.exe` — ve o dosyanın içinde bash yoktur. Sihirbaz bu yüzden burada,
paketin içinde yaşıyor.

İki yüzey, tek gövde: TUI (`usage-tracker setup`) ve tarayıcı (`setup --ui`) aynı
`probe/preview/do/undo` fonksiyonlarını çağırır — `setup.sh`'ın öğrettiği ders buydu,
ayrışmasınlar diye. Sözleşme de aynı: **stdout yalnız JSON**, insan satırları çağırana.

Kural — her adım üç şeyi birden yapabilmeli:
  · `preview` → tam olarak ne yazılacağını **yazmadan önce** göster (dosya yolu + içerik)
  · `do`      → uygula, neyin değiştiğini söyle
  · `undo`    → geri al; kullanıcı denemekten korkmasın

Yazılan her şey kullanıcının kendi alanında: `%LOCALAPPDATA%` / `%APPDATA%` / `~/.local`.
Yönetici hakkı istenmez, sistem dizinlerine dokunulmaz, kurulum dizinine yazılmaz.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

from . import platform as _paths
from . import settings as _settings

APP_NAME = 'usage-tracker'
PANEL_PORT = int(os.environ.get('USAGE_PORT', '8770'))
PANEL_URL = f'http://127.0.0.1:{PANEL_PORT}'

#: Sihirbazın yazdığı her dosya bu işareti taşır — `undo` neyi silmeye izinli olduğunu
#: dosyanın **içeriğinden** anlar, adından değil. Kullanıcının kendi yazdığı aynı adlı bir
#: dosyayı silmek, geri alınabilir bir sihirbazın yapabileceği en kötü şeydir.
STAMP = 'generated by usage-tracker setup'


# ── ortak yardımcılar ─────────────────────────────────────────────────────────
def is_windows() -> bool:
    return _paths.is_windows()


def binary_path() -> Path:
    """Kullanıcının çalıştırdığı şey: donmuş pakette `.exe`, kaynakta `server.py`."""
    if _paths.is_frozen():
        return Path(sys.executable).resolve()
    return (Path(__file__).resolve().parent.parent / 'server.py')


def launch_command() -> list:
    """Sunucuyu başlatan komut — donmuş ikilide tek parça, kaynakta yorumlayıcı + script."""
    binary = binary_path()
    return [str(binary)] if _paths.is_frozen() else [sys.executable, str(binary)]


def child_env() -> dict:
    """Aynı ikiliyi ayrı bir süreç olarak başlatırken ortamdan **PyInstaller'ın kendi
    değişkenlerini** çıkar.

    Tek dosyalık paket kendini `/tmp/_MEIxxxx` altına açar ve bu yolu `_PYI_APPLICATION_HOME_DIR`
    ile çocuklarına miras bırakır — "aynı paketten yeniden çalıştırdın, ikinci kez açma" demek
    için. Ama biz çocuğu **ebeveynden uzun yaşasın** diye başlatıyoruz: ebeveyn çıkınca o dizini
    siler, çocuk hâlâ oradan okumaya çalışır. Sonuç, tanıdık bir tabloydu — `/v1/usage` 200
    (kod zaten bellekte), panelin **her dosyası 404** (diskten okunuyor): araç çalışıyor,
    ekran boş. Ölçüldü 2026-08-13, donmuş Linux ikilisinde.
    """
    stripped = {k: v for k, v in os.environ.items()
                if not k.startswith('_PYI_') and k != '_MEIPASS2'}
    return stripped


def install_dir() -> Path:
    """İkilinin kalıcı adresi. `Program Files` bilinçli DEĞİL: oraya yazmak yönetici ister
    ve bu araç yönetici istemez — kullanıcı kendi hesabına kurar, kendi hesabından siler."""
    if is_windows():
        return _paths._windows_base('LOCALAPPDATA') / 'Programs' / APP_NAME
    return _paths.home() / '.local' / 'bin'


def installed_binary() -> Path:
    return install_dir() / ('usage-tracker.exe' if is_windows() else 'usage-tracker')


def is_installed() -> bool:
    return installed_binary().exists()


def running_from_install() -> bool:
    try:
        return binary_path() == installed_binary().resolve()
    except OSError:
        return False


def is_first_run() -> bool:
    """Bu makinede kurulum hiç yapılmamış mı?

    Ayrı bir "kuruldu" damgası tutulmuyor: kurulumun kendisi zaten iki iz bırakıyor
    (kalıcı yere kopya + oturum açılışı kaydı). Üçüncü bir durum dosyası, o dosya ile
    gerçeklik arasında sessizce ayrışabilecek bir yer daha demek olurdu.
    """
    try:
        return not is_installed() and not _autostart_path().exists()
    except OSError:
        return False


def server_alive(timeout: float = 1.5) -> bool:
    try:
        with urllib.request.urlopen(f'{PANEL_URL}/v1/usage', timeout=timeout) as r:
            return r.status == 200
    except (urllib.error.URLError, OSError, ValueError):
        return False


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    _paths.atomic_write_text(path, text)


def _is_ours(path: Path) -> bool:
    try:
        return path.exists() and STAMP in path.read_text(encoding='utf-8', errors='replace')
    except OSError:
        return False


def _backup(path: Path) -> Path | None:
    """Bizim olmayan bir dosyanın üzerine yazmadan önce kopyasını al — ve **var olan yedeği
    ezme**: ikinci çalıştırma, ilk çalıştırmanın kurtardığı orijinali yok ederdi. Bu tam
    olarak `service.sh` ile kurulmuş bir systemd unit'inin başına gelecek olan şeydi."""
    if not path.exists() or _is_ours(path):
        return None
    backup = path.with_name(path.name + '.bak-usage-tracker')
    if backup.exists():
        return backup
    try:
        shutil.copy2(path, backup)
    except OSError:
        return None
    return backup


def _remove_if_ours(path: Path) -> bool:
    """Yalnız bizim yazdığımızı sil. İçerikte damga yoksa dokunma — kullanıcının aynı adı
    taşıyan kendi dosyası olabilir ve geri alma bir veri kaybı yolu olamaz."""
    if not path.exists():
        return False
    try:
        if STAMP not in path.read_text(encoding='utf-8', errors='replace'):
            return False
    except OSError:
        return False
    path.unlink()
    return True


# ── adım: install (ikiliyi kalıcı bir yere koy) ───────────────────────────────
def _probe_install() -> dict:
    return {
        'installed': is_installed(),
        'target': str(installed_binary()),
        'running_from': str(binary_path()),
        'running_from_install': running_from_install(),
        'frozen': _paths.is_frozen(),
    }


def _preview_install() -> dict:
    if not _paths.is_frozen():
        return {'lines': [
            'Nothing to copy: this is a source checkout, not a single-file build.',
            f'The wizard will point every shortcut at {binary_path()}.']}
    return {'lines': [
        f'copy  {binary_path()}',
        f'  to  {installed_binary()}',
        'The file you downloaded stays where it is; this is a copy, not a move.']}


def _do_install(opts: dict) -> dict:
    if not _paths.is_frozen():
        return {'ok': True, 'changed': False,
                'messages': ['info|source checkout — nothing to copy']}
    if running_from_install():
        return {'ok': True, 'changed': False,
                'messages': [f'info|already running from {installed_binary()}']}
    target = installed_binary()
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        shutil.copy2(binary_path(), target)
    except OSError as exc:
        # Çalışan .exe'nin üzerine yazılamaz (Windows dosyayı kilitler) — bu, kullanıcının
        # zaten kurulu sürümü çalıştırırken güncellemeye çalıştığı hâldir; söyle, yalan söyleme.
        return {'ok': False, 'changed': False,
                'messages': [f'error|could not copy to {target}: {exc.__class__.__name__} — '
                             'if an older copy is running, close it first']}
    return {'ok': True, 'changed': True, 'messages': [f'ok|installed to {target}']}


def _undo_install() -> dict:
    target = installed_binary()
    if not target.exists():
        return {'ok': True, 'changed': False, 'messages': ['info|nothing installed']}
    if binary_path() == target:
        # Kendi altındaki zemini çekmek: Windows çalışan dosyayı silmez, Linux siler ve
        # süreç yaşamaya devam eder. İkisinde de doğru cevap "sen kapatınca sil".
        return {'ok': False, 'changed': False,
                'messages': ['error|this is the copy that is running — close it, then run '
                             'undo from the downloaded file']}
    try:
        target.unlink()
    except OSError as exc:
        return {'ok': False, 'changed': False, 'messages': [f'error|{exc}']}
    return {'ok': True, 'changed': True, 'messages': [f'ok|removed {target}']}


# ── adım: autostart ───────────────────────────────────────────────────────────
def _startup_dir() -> Path:
    return (_paths._windows_base('APPDATA')
            / 'Microsoft' / 'Windows' / 'Start Menu' / 'Programs' / 'Startup')


def _win_autostart_file() -> Path:
    return _startup_dir() / 'usage-tracker.vbs'


def _win_autostart_body() -> str:
    """Neden VBS: `.exe` bir konsol uygulaması, oturum açılışında siyah bir pencere açar ve
    kullanıcı onu kapatınca sunucu ölür. `WScript.Shell.Run(..., 0, False)` pencereyi hiç
    göstermez. Alternatifi ikiliyi penceresiz derlemekti — o da CLI'ı kullanılamaz yapardı."""
    exe = installed_binary() if is_installed() else binary_path()
    base = f'""{exe}""' if _paths.is_frozen() else f'""{sys.executable}"" ""{exe}""'
    # `--no-open`: bu, oturum açılışında sessizce koşan kopya. Tarayıcı açmak kullanıcının
    # her açılışta kapatacağı bir pencere demekti.
    cmd = f'{base} --no-open'
    return (f"' {STAMP}\r\n"
            "' Runs the usage-tracker server at logon with no console window.\r\n"
            "' Remove this file (or run: usage-tracker setup --undo autostart) to stop it.\r\n"
            'CreateObject("WScript.Shell").Run "' + cmd + '", 0, False\r\n')


def _systemd_unit_path() -> Path:
    return _paths.config_dir().parent / 'systemd' / 'user' / 'usage-tracker.service'


def _systemd_unit_body() -> str:
    cmd = ' '.join(f'"{part}"' if ' ' in part else part for part in launch_command())
    cmd += ' --no-open'
    return (f'# {STAMP}\n'
            '[Unit]\n'
            'Description=usage-tracker — AI usage/limit/spend server (loopback :8770)\n'
            'Documentation=https://github.com/ihsandeniz/usage-tracker\n'
            'After=default.target\n\n'
            '[Service]\n'
            'Type=simple\n'
            'EnvironmentFile=-%h/.config/usage-tracker/env\n'
            f'ExecStart={cmd}\n'
            'Restart=on-failure\n'
            'RestartSec=5\n\n'
            '[Install]\n'
            'WantedBy=default.target\n')


def _autostart_path() -> Path:
    return _win_autostart_file() if is_windows() else _systemd_unit_path()


def _autostart_body() -> str:
    return _win_autostart_body() if is_windows() else _systemd_unit_body()


def _probe_autostart() -> dict:
    path = _autostart_path()
    return {'enabled': path.exists(), 'path': str(path),
            'mechanism': 'Startup folder (hidden launcher)' if is_windows()
                         else 'systemd user service',
            'running': server_alive()}


def _preview_autostart() -> dict:
    path = _autostart_path()
    head = [f'write {path}']
    if path.exists() and not _is_ours(path):
        head.append(f'⚠ this file already exists and was not written by this wizard — '
                    f'a copy will be kept at {path.name}.bak-usage-tracker')
    return {'lines': head + [''] + _autostart_body().replace('\r\n', '\n').split('\n')}


def _do_autostart(opts: dict) -> dict:
    path, body = _autostart_path(), _autostart_body()
    saved = _backup(path)
    _write(path, body)
    messages = [f'ok|autostart written to {path}']
    if saved:
        messages.insert(0, f'warn|your previous file was kept at {saved}')
    if not is_windows():
        # systemd'yi biz *deneriz*; yoksa dosya zaten yerinde ve kullanıcı kendi enable eder.
        rc, out = _run(['systemctl', '--user', 'enable', '--now', 'usage-tracker.service'])
        messages.append(('ok|' if rc == 0 else 'warn|') +
                        ('service enabled and started' if rc == 0
                         else f'unit written, but systemctl said: {out.strip()[:120]}'))
    else:
        messages.append('info|it will start at your next logon — start it now from the '
                        'panel step, or just run usage-tracker')
    return {'ok': True, 'changed': True, 'messages': messages}


def _undo_autostart() -> dict:
    path = _autostart_path()
    messages, changed = [], False
    # Servisi durdurmadan ÖNCE dosyanın bizim olduğunu doğrula. Sırayı ters yapmak, bu
    # sihirbazın hiç yazmadığı bir autostart'ı (ör. `service.sh install` ile kurulmuş bir
    # unit'i) durdurup devre dışı bırakır — geri alma, dokunmadığı şeyi bozamaz.
    # Ölçüldü 2026-08-13: ilk sürüm tam bunu yaptı ve geliştirme makinesindeki servisi kapattı.
    if not is_windows() and _is_ours(path):
        _run(['systemctl', '--user', 'disable', '--now', 'usage-tracker.service'])
    if _remove_if_ours(path):
        changed = True
        messages.append(f'ok|removed {path}')
    elif path.exists():
        messages.append(f'warn|left {path} alone — it was not written by this wizard')
    else:
        messages.append('info|no autostart entry')
    return {'ok': True, 'changed': changed, 'messages': messages}


# ── adım: shortcut (panele bir tık) ───────────────────────────────────────────
def _shortcut_path() -> Path:
    if is_windows():
        return (_paths._windows_base('APPDATA') / 'Microsoft' / 'Windows'
                / 'Start Menu' / 'Programs' / 'usage-tracker.cmd')
    return _paths.home() / '.local' / 'share' / 'applications' / 'usage-tracker.desktop'


def _shortcut_body() -> str:
    """`.lnk` üretmek COM ister (pywin32) — sıfır bağımlılık sözü onu kapatıyor. `.cmd` ve
    `.desktop` düz metindir, Başlat menüsünde/uygulama listesinde görünür ve okunabilir."""
    cmd = ' '.join(f'"{p}"' for p in launch_command())
    if is_windows():
        return (f'@echo off\r\nrem {STAMP}\r\n'
                'rem Opens the panel; starts the server first if nothing is listening.\r\n'
                f'{cmd} panel\r\n')
    exec_cmd = ' '.join(launch_command()) + ' panel'
    return ('[Desktop Entry]\n'
            f'# {STAMP}\n'
            'Type=Application\n'
            'Name=usage-tracker\n'
            'Comment=AI usage, limits and real spend in one panel\n'
            f'Exec={exec_cmd}\n'
            'Terminal=false\n'
            'Categories=Utility;Development;\n')


def _probe_shortcut() -> dict:
    path = _shortcut_path()
    return {'exists': path.exists(), 'path': str(path)}


def _preview_shortcut() -> dict:
    path = _shortcut_path()
    head = [f'write {path}']
    if path.exists() and not _is_ours(path):
        head.append(f'⚠ exists already — a copy will be kept at {path.name}.bak-usage-tracker')
    return {'lines': head + [''] + _shortcut_body().replace('\r\n', '\n').split('\n')}


def _do_shortcut(opts: dict) -> dict:
    path = _shortcut_path()
    saved = _backup(path)
    _write(path, _shortcut_body())
    if not is_windows():
        try:
            path.chmod(0o755)
        except OSError:
            pass
    messages = [f'ok|shortcut written to {path}']
    if saved:
        messages.insert(0, f'warn|your previous file was kept at {saved}')
    return {'ok': True, 'changed': True, 'messages': messages}


def _undo_shortcut() -> dict:
    path = _shortcut_path()
    if _remove_if_ours(path):
        return {'ok': True, 'changed': True, 'messages': [f'ok|removed {path}']}
    if path.exists():
        return {'ok': True, 'changed': False,
                'messages': [f'warn|left {path} alone — not written by this wizard']}
    return {'ok': True, 'changed': False, 'messages': ['info|no shortcut']}


# ── adım: keys ────────────────────────────────────────────────────────────────
KNOWN_KEYS = tuple(sorted({name for names in _settings.PROVIDER_ENV.values()
                           for name in names}))


def env_file() -> Path:
    """Linux'ta `setup.sh`'ın yazdığı **aynı** dosya. İki sihirbazın iki ayrı anahtar deposu
    olsaydı, kullanıcı anahtarını yazar ve diğerinin okumadığını günler sonra fark ederdi."""
    return _paths.config_dir() / 'env'


def _win_env_read() -> dict:
    """HKCU\\Environment — yalnız **hangi adların dolu olduğu**. Değer okunur ama asla
    döndürülmez; bu fonksiyonun çıktısı hata raporuna yapıştırılabilir olmalı."""
    try:
        import winreg
    except ImportError:
        return {}
    out = {}
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, 'Environment') as key:
            for name in KNOWN_KEYS:
                try:
                    value, _ = winreg.QueryValueEx(key, name)
                    out[name] = bool(value)
                except FileNotFoundError:
                    out[name] = False
    except OSError:
        return {}
    return out


def _win_env_write(pairs: dict) -> list:
    import winreg
    messages = []
    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, 'Environment') as key:
        for name, value in pairs.items():
            if value:
                winreg.SetValueEx(key, name, 0, winreg.REG_SZ, value)
                messages.append(f'ok|{name} set for your user account')
            else:
                try:
                    winreg.DeleteValue(key, name)
                    messages.append(f'ok|{name} removed')
                except FileNotFoundError:
                    pass
    _win_broadcast_env()
    messages.append('info|already-open programs keep the old environment — '
                    'a new terminal (or logon) sees the change')
    return messages


def _win_broadcast_env() -> None:
    """`setx` bunu kendisi yapar, biz `winreg` kullandığımız için elle yapıyoruz: yayın
    olmadan yeni açılan Explorer/terminal bile eski ortamı miras alır."""
    try:
        import ctypes
        HWND_BROADCAST, WM_SETTINGCHANGE, SMTO_ABORTIFHUNG = 0xFFFF, 0x001A, 0x0002
        ctypes.windll.user32.SendMessageTimeoutW(
            HWND_BROADCAST, WM_SETTINGCHANGE, 0, ctypes.c_wchar_p('Environment'),
            SMTO_ABORTIFHUNG, 2000, None)
    except Exception:                       # yayın başarısızsa anahtar yine de yazılıdır
        pass


def _env_file_read() -> dict:
    path, out = env_file(), {name: False for name in KNOWN_KEYS}
    if not path.exists():
        return out
    try:
        for line in path.read_text(encoding='utf-8', errors='replace').splitlines():
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            name, _, value = line.partition('=')
            name = name.strip()
            if name in out:
                out[name] = bool(value.strip().strip('"\''))
    except OSError:
        pass
    return out


def _env_file_write(pairs: dict) -> list:
    """Satır satır düzenle, dosyayı yeniden akıtma: kullanıcının yorumları ve bizim
    tanımadığımız değişkenleri **olduğu yerde** kalır (`packaging/env_edit.py` dersi)."""
    path = env_file()
    lines = (path.read_text(encoding='utf-8', errors='replace').splitlines()
             if path.exists() else [f'# {STAMP} — provider API keys, one per line'])
    messages = []
    for name, value in pairs.items():
        pattern = f'{name}='
        kept = []
        for line in lines:
            if line.strip().startswith(pattern):
                continue                    # eski satırı düşür, yenisi aşağıda
            kept.append(line)
        lines = kept
        if value:
            lines.append(f'{name}={value}')
            messages.append(f'ok|{name} written to {path}')
        else:
            messages.append(f'ok|{name} removed from {path}')
    _write(path, '\n'.join(lines) + '\n')
    try:
        path.chmod(0o600)                   # dosya anahtar taşıyor: yalnız sahibi okusun
    except OSError:
        pass
    return messages


def _probe_keys() -> dict:
    stored = _win_env_read() if is_windows() else _env_file_read()
    shell_only = [name for name in KNOWN_KEYS
                  if os.environ.get(name) and not stored.get(name)]
    return {
        'store': 'HKCU\\Environment (your user account)' if is_windows() else str(env_file()),
        'known': list(KNOWN_KEYS),
        'set': [name for name in KNOWN_KEYS if stored.get(name)],
        'shell_only': shell_only,
        'providers': _settings.key_status(),
    }


def _preview_keys() -> dict:
    return {'lines': [
        f'store: {_probe_keys()["store"]}',
        'Keys are written by name and value; the wizard never prints a value back.',
        'Nothing is sent anywhere — the tool talks to a provider only when you ask it to.']}


def _do_keys(opts: dict) -> dict:
    pairs = {name: value for name, value in (opts.get('keys') or {}).items()
             if name in KNOWN_KEYS}
    unknown = sorted(set(opts.get('keys') or {}) - set(KNOWN_KEYS))
    if not pairs:
        return {'ok': False, 'changed': False,
                'messages': [f'error|no known key names given'
                             + (f' (unknown: {", ".join(unknown)})' if unknown else '')]}
    try:
        messages = _win_env_write(pairs) if is_windows() else _env_file_write(pairs)
    except OSError as exc:
        return {'ok': False, 'changed': False, 'messages': [f'error|{exc}']}
    if unknown:
        messages.append(f'warn|ignored unknown names: {", ".join(unknown)}')
    return {'ok': True, 'changed': True, 'messages': messages}


def _undo_keys() -> dict:
    stored = _win_env_read() if is_windows() else _env_file_read()
    present = {name: '' for name, is_set in stored.items() if is_set}
    if not present:
        return {'ok': True, 'changed': False, 'messages': ['info|no keys stored']}
    messages = _win_env_write(present) if is_windows() else _env_file_write(present)
    return {'ok': True, 'changed': True, 'messages': messages}


# ── adım: verify ──────────────────────────────────────────────────────────────
def _probe_verify() -> dict:
    return {'server': server_alive(), 'url': PANEL_URL}


def _preview_verify() -> dict:
    return {'lines': ['Runs the same checks as `usage-tracker doctor` and writes nothing.']}


def _do_verify(opts: dict) -> dict:
    from . import cli
    report = cli.collect_doctor(_DoctorArgs())
    messages = []
    for check in report['checks']:
        level = {'ok': 'ok', 'warn': 'warn', 'fail': 'error'}[check['level']]
        messages.append(f'{level}|{check["title"]}: {check["detail"]}')
    return {'ok': report['problems'] == 0, 'changed': False, 'messages': messages,
            'report': report}


class _DoctorArgs:
    """`collect_doctor` bir argparse namespace bekliyor; sihirbaz ona ağa çıkmayan
    varsayılanları veriyor (`--probe` yok: kurulum sırasında sağlayıcı API'lerine gitmek
    kullanıcının beklemediği bir ağ trafiğidir)."""
    json = True
    probe = False
    url = None
    local = False


# ── adım tablosu ──────────────────────────────────────────────────────────────
#: Adımlar fonksiyon **adıyla** tutuluyor, nesnesiyle değil: tablo import anında bağlansaydı
#: bir adımı yerinden almak (test, ya da ileride bir platform geçersiz kılması) tabloyu değil
#: yalnız modül niteliğini değiştirir ve çağrı eski fonksiyona giderdi — sessizce.
_STEPS = {
    'install':   ('_probe_install',   '_preview_install',   '_do_install',   '_undo_install'),
    'autostart': ('_probe_autostart', '_preview_autostart', '_do_autostart', '_undo_autostart'),
    'shortcut':  ('_probe_shortcut',  '_preview_shortcut',  '_do_shortcut',  '_undo_shortcut'),
    'keys':      ('_probe_keys',      '_preview_keys',      '_do_keys',      '_undo_keys'),
    'verify':    ('_probe_verify',    '_preview_verify',    '_do_verify',    None),
}


def _fn(step: str, slot: int):
    name = _STEPS[step][slot]
    return globals()[name] if name else None

#: `--auto`'nun koşacağı adımlar. `keys` **bilinçli dışarıda**: otomatik mod kullanıcıya
#: sormadan çalışır ve bir anahtarı sormadan yazmanın yolu yoktur.
AUTO_STEPS = ('install', 'autostart', 'shortcut', 'verify')

STEP_TITLES = {
    'install':   'Put the program somewhere permanent',
    'autostart': 'Start it automatically when you log in',
    'shortcut':  'Add a shortcut that opens the panel',
    'keys':      'Provider API keys (optional)',
    'verify':    'Check that everything works',
}


def steps() -> list:
    """Bu makinede anlamlı adımlar, sırayla."""
    return [{'id': sid, 'title': STEP_TITLES[sid]} for sid in _STEPS]


def probe() -> dict:
    binary = binary_path()
    return {
        'ok': True,
        'platform': 'windows' if is_windows() else _paths.system(),
        'frozen': _paths.is_frozen(),
        'binary': str(binary),
        'panelUrl': PANEL_URL,
        'setupSh': (Path(__file__).resolve().parent.parent / 'setup.sh').exists()
                   and not is_windows(),
        'steps': steps(),
        'install': _probe_install(),
        'autostart': _probe_autostart(),
        'shortcut': _probe_shortcut(),
        'keys': _probe_keys(),
        'verify': _probe_verify(),
    }


def preview(step: str) -> dict:
    if step not in _STEPS:
        return {'ok': False, 'error': f'unknown step: {step}'}
    out = _fn(step, 1)()
    out.update({'ok': True, 'step': step})
    return out


def do(step: str, opts: dict | None = None) -> dict:
    if step not in _STEPS:
        return {'ok': False, 'changed': False, 'messages': [f'error|unknown step: {step}']}
    result = _fn(step, 2)(opts or {})
    result['step'] = step
    return result


def undo(step: str) -> dict:
    if step not in _STEPS:
        return {'ok': False, 'changed': False,
                'messages': [f'error|unknown step: {step}']}
    if _STEPS[step][3] is None:
        return {'ok': False, 'changed': False,
                'messages': [f'error|nothing to undo for step: {step} (it writes nothing)']}
    result = _fn(step, 3)()
    result['step'] = step
    return result


def auto(opts: dict | None = None) -> dict:
    """Önerilen kurulum. Başarısız adım **yutulmaz** — `setup.sh --auto`'nun ilk sürümü
    yutuyordu ve kullanıcı kurulumun bittiğini sanıyordu."""
    results, failed = [], []
    for step in AUTO_STEPS:
        result = do(step, opts)
        results.append(result)
        if not result.get('ok'):
            failed.append(step)
    return {'ok': not failed, 'failed': failed, 'results': results}


def uninstall() -> dict:
    """Sihirbazın yazdığı her şeyi geri al. **Anahtarlar ve veri kalır** — onları silmek
    kullanıcının ayrıca isteyeceği bir şeydir, kurulumu geri almanın yan etkisi değil."""
    results = [undo(step) for step in ('shortcut', 'autostart')]
    return {'ok': all(r.get('ok') for r in results), 'results': results,
            'kept': {'keys': str(env_file()) if not is_windows() else 'HKCU\\Environment',
                     'data': [str(_paths.config_dir()), str(_paths.state_dir())]}}


def _run(cmd: list) -> tuple:
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8',
                              errors='replace', timeout=30)
        return proc.returncode, (proc.stdout or '') + (proc.stderr or '')
    except (OSError, subprocess.SubprocessError) as exc:
        return 1, str(exc)


if __name__ == '__main__':                  # hata ayıklama için: probe'u bas
    print(json.dumps(probe(), ensure_ascii=False, indent=2))
